### ISSUE TITLE
Research existing implementations of comment plugins

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-comments-react#1]
Some things like `disqus-react`, `simple-react-comments` and others. See if we can fork an existing repo to get going.

Output should be a Notion doc.

**Comment by michaelsena** [comment]
How can we describe the subject of the thread? Can we let devs pass in an option, or should we always make it the site page URL?

**Comment by oznekenzo** [comment]
@michaelsena what do you mean exactly by the subject of the thread?
Benchmarking now with other products and disqus for example limits one discussion per page, and the developer would make it apparent that the discussion is relevant to the contents of the page
