### ISSUE TITLE
Update, test, and merge "reactions and replies" feature from hackathon submission

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-comments-react#24]

**Comment by oznekenzo** [comment]
- [x] Merge to 1.16.1
- [x] Make replies smaller
- [x] Move votes 
- [x] Unify actions
- [x] make space efficient
- [ ] ~move delete to inside controller~
- [x] nicer solution to inline reply comment input
- [x] style input loading process
- [x] Style reactions
- [x] do not delete nested reply, replace with a sign saying "This post was removed by user (or moderator)" - only if there is a reply to that comment
- [x] maintain deleted comment hierarchy
- [x] style deleted comment hierarchy
- [x] deleting reply with nested reply not working
- [x] double clicking inline emoji picker is not closing
- [x] show by color your previous vote
- [x] only show comment control when it should
- [x] only one reply input open at a time (move to higher component and use postId to specify)
- [x] Reverse order of reactions
- [x] left align better, including replies, and right align as well
- [x] "Extend" timeline to input of top level comment to next line
- [x] handle emoji reactions that run off width
- [ ] ~does deleting comment delete all nested reactions??? (you can't these posts belong to different authors)~
- [x] Clicking reaction when not logged in only logs me in, doesnt remove the reaction 
- [x] mobile responsive
- [ ] onClickOutside replies
