### ISSUE TITLE
"Failed to compile" error with node-sass

### ISSUE THREAD

**Issue by fvictorio** [3box/3box-comments-react#26]
## Steps to reproduce

1. Create a react application with `create-react-app`
2. Install `3box-comments-react`
3. Import it in some file

Result:

```
./node_modules/3box-comments-react/lib/index.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./node_modules/3box-comments-react/lib/index.scss)
To import Sass files, you first need to install node-sass.
Run `npm install node-sass` or `yarn add node-sass` inside your workspace.
```

Looking into `node_modules/3box-comments-react/lib/index.js` I noticed a `require("./index.scss")` so I guess the problem is webpack not properly creating the build. Weird, since the `sass-loader` seems to be used correctly in Webpack's config.

I guess (but didn't try it) that this can be solved by configuring sass in the app that uses this component, but I think this should be fixed in the library.

**Comment by oznekenzo** [comment]
@fvictorio I've moved node-sass from dev-dep to dep, this will fix the issue youre seeing (3box-comments-react@0.0.8).  We updated the configs for our plugins recently to build when the dapp its integrated in build, so there might be more dependency issues. If you're able to report it, I'll fix them right away.
Thanks for reporting

**Comment by fvictorio** [comment]
Thanks! It works now. Two new issues:

- The "Decentralized comments by" part seems broken (worked fine with previous version)

  ![image](https://user-images.githubusercontent.com/417134/72286260-8ae15580-3623-11ea-85fa-74f7a60d1e76.png)

- A lot of `Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.` errors in the console.

**Comment by oznekenzo** [comment]
@fvictorio that's odd, you might have a style rule overriding the component.  I'll update it to have more stringent rules

**Comment by oznekenzo** [comment]
The a tag warning is annoying but will still work on most browsers as expected - but I will add using another method to avoid the warning log altogether to an issue to be completed later

**Comment by oznekenzo** [comment]
@fvictorio have updated the css in a new version.
