### ISSUE TITLE
loginFunction never getting called

### ISSUE THREAD

**Issue by tibetsprague** [3box/3box-comments-react#31]
I am unable to get loginFunction to fire, no matter what set of props I pass in to the ThreeBoxComments component. 

This means I will need to hide the comments until users click some kind of login to 3box button which is not ideal.

**Comment by oed** [comment]
Thanks for reporting @tibetsprague. Would you mind having a look at this @oznekenzo?

**Comment by oznekenzo** [comment]
will do

**Comment by oznekenzo** [comment]
@tibetsprague an updated lib with the fix that addresses your problem is at version `3.0.1` - thanks for reporting

**Comment by tibetsprague** [comment]
Thank you! This works. Only thing is i think the docs should be updated because you have to pass in the ethereum prop otherwise loginFunc still doesnt work
