### ISSUE TITLE
Implement auth/sign-in flows

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-comments-react#4]
How can we connect this component to the broader site log-in?

**Comment by oznekenzo** [comment]
Discussed and deemed not necessary.  Login will be handled by parent dapp, not this component. though there should be some message to the user when attempting to interact without already having logged in.

**Comment by oznekenzo** [comment]
- [x] A) user is already signed in to web3 and 3box
- [x] B) user signs in to 3box at global state using developer function
- [x] C) user signs in at component level
