### ISSUE TITLE
Polish UI for comments plugin

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-comments-react#5]

**Comment by oznekenzo** [comment]
- [x] break word in comment not working, small words should just go to next line
- [x] shift return should allow line break
- [x] comment count should update
- [x] purple should stay blue
- [x] loadMore count prop
- [x] move footer to left
- [x] input profile picture not rendering prof pic
- [x] load more within a larger comment (show more comment) [No]
- [x] dev formats entire url and passes to component, two conventions and document
- [x] add circle around empty profile pic
- [x] display delete on mobile
- [x] send button on mobile, enter on mobile will do line break
- [x] update my profile in input after i log in
- [x] admin delete not option not showing up
