### ISSUE TITLE
Test comments plugin

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-comments-react#6]
Test in it's own react app, another react app, and on mobile envs

**Comment by oznekenzo** [comment]
- [x] needs mobile styling

**Comment by oznekenzo** [comment]
- [x] When box object received, logged in status should be updated
- [x] currentUserAddr needs to be passed in usecase A & B
- [x] test passing profile to component
- [x] Current user profile fetched doesn't update in input
- [x] Case A
- [x] Case B
- [x] Order posts chronologically
- [x] Case C
- [x] Prevent and add warning to comment without web3
- [x] threads not fetching on new user or cleared cache [only on clear cache - this is fine]
- [x] New profile isnt fetched and in thread when posting
- [x] Mobile 
- [x] Add error msgs
- [x] Try passing incorrect values / props to component
- [ ] Existing dapp 1
- [ ] Existing dapp 2
